CREATE DATABASE LOGIN_DATA;

CREATE TABLE LOGIN_TBL
(
USERNAME VARCHAR(50) NOT NULL,
PASS NVARCHAR(50) NOT NULL
);
SELECT * FROM LOGIN_TBL;
insert into LOGIN_TBL values('Admin123@gmail.com','123456789q')